name: thousand_counter
description: "Counter for card game Thousand"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  talker_flutter: ^5.1.13
  uuid: ^4.5.2
  recase: ^4.1.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  go_router: ^14.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  talker_riverpod_logger: ^5.0.1
  flutter_slidable: ^4.0.3
  flutter_localizations:
    sdk: flutter
  intl: any
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1

flutter:
  uses-material-design: true
  generate: true
