name: thousand_counter
description: "Counter for card game Thousand"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  talker: ^5.1.10
  uuid: ^4.5.2
  recase: ^4.1.0
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  go_router: ^14.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
